# Generated by Django 2.2.1 on 2020-07-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Example',
            new_name='Example1',
        ),
        migrations.AlterModelTable(
            name='example1',
            table='Example1',
        ),
    ]
