# Generated by Django 2.2.1 on 2020-07-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0002_auto_20200702_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='example1',
            name='addres',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='example1',
            name='curp',
            field=models.CharField(default='matm962905hcstmr08', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example1',
            name='year',
            field=models.CharField(default='22', max_length=2),
            preserve_default=False,
        ),
    ]
