# Generated by Django 2.2.1 on 2020-07-04 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0003_auto_20200703_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='addres',
            field=models.CharField(default='queagrego', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example1',
            name='curp',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='example1',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
