# Generated by Django 2.2.1 on 2020-07-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0004_auto_20200704_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example1',
            old_name='addres',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='example1',
            old_name='year',
            new_name='edad',
        ),
    ]
