# Generated by Django 2.2.1 on 2020-07-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0005_auto_20200704_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='curp',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='example1',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='example1',
            name='edad',
            field=models.IntegerField(default=1),
        ),
    ]
