# Generated by Django 2.2.1 on 2020-07-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0006_auto_20200704_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='curp',
            field=models.TextField(default='', max_length=16),
        ),
    ]
